CREATE TABLE `system`.`ELEGENT_STUDENTS` (
  `FIRSTNAME` VARCHAR(45) NULL,
  `LASTNAME` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` VARCHAR(45) NULL,
  `ZIP` VARCHAR(45) NULL,
  `PHONENUM` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `GENDER` VARCHAR(45) NULL
);